alias rf := run-file
alias d := default


# NOTE: Default command to run to view the list of all available commands
default:
    @just --list


# NOTE: Example usage: just run-file (or rf) some_test_file.py (this is the file with tests)
run-file file:
    @echo "{{BG_BLUE}}INFO:{{NORMAL}} Running unit tests for the following file: {{file}}"

    @if [ ! -f "{{file}}" ]; then \
        echo "{{BG_RED}}ERROR:{{NORMAL}} The file '{{file}}' does not exist."; \
        exit 1; \
    fi

    @if [ -z "$(which uv)" ]; then \
        echo "{{BG_RED}}ERROR:{{NORMAL}} uv is not installed. Please install uv, if you intend to use uv instead of pytest standalone."
        exit 1; \
    else \
        @uv run pytest -v -s {{file}} \
        exit 1; \
    fi
    

    @if [ -z "$(which pytest)" ]; then \
        echo "{{BG_RED}}ERROR:{{NORMAL}} pytest is not installed. Please install pytest to run the tests."; \
        exit 1; \
    else \
        @pytest -v -s {{file}} \
        exit 1; \
    fi

