[project]
name = "00-py"
version = "0.1.0"
description = "Directory for LeetCode solutions done using python with pytest for unit tests."
requires-python = ">=3.12"
dependencies = [
    "pytest>=8.4.1",
]
