alias rf := run-file
alias d := default


# NOTE: Default command to run to view the list of all available commands
default:
    @just --list


# NOTE: Example usage: just run-file (or rf) some_test_file.py (this is the file with tests)
run-file file:
    @echo "{{BG_BLUE}}INFO:{{NORMAL}} Running unit tests for the following file: {{file}}"

    @if [ ! -f "package.json" ]; then \
        echo "{{BG_RED}}ERROR:{{NORMAL}} package.json not found. Please run this command from the project root."; \
        exit 1; \
    fi

    @if [ ! -d "node_modules" ]; then \
        echo "{{BG_RED}}ERROR:{{NORMAL}} node_modules not found. Please run 'npm install' first."; \
        exit 1; \
    fi

    @if [ ! -f "test/{{file}}" ]; then \
        echo "{{BG_RED}}ERROR:{{NORMAL}} The file '{{file}}' does not exist."; \
        exit 1; \
    fi

    @NODE_OPTIONS=--experimental-vm-modules npx jest "test/{{file}}" --config="{}" --verbose
